review_dir: /home/<user>/code-reviews/drupal7
review_filetype: [js, html, php, css, module, install, inc]

strings: ["$form_state['values']", "$form_state['input']", "eval", "mysql", "query", "$_GET", "$_POST", "$_REQUEST", "check_plain", "filter_xss", "filter_xss_admin", "check_markup"]
good_strings: ["$form_state['values']", "$_POST", "$_REQUEST", "check_plain", "filter_xss", "filter_xss_admin", "check_markup"]
bad_strings: ["eval", "$_GET", "$form_state['input']"]
sqli_strings: ["mysql", "query"]

debug_messages: False